### ISSUE TITLE
Notes from meeting with Amanda on Thursday evening

### ISSUE THREAD

**Issue by RobStallion** [dwyl/bestevidence#430]
After speaking with Amanda and demoing the current state of the app, the following points were things that she would like to be worked on in a further sprint.

(the points with lines through have already been completed but were not merged at the time of the demo)

### Search page
- [x] Remove links from the right of the recent search
- [x] Change Recent searches to recent questions
- [x] Button changes. Put all 3 on same line and make same colour

### Notes page
- Change notes page title to BEARs (This needs to be changed on the navbar as well) -1h
- Ability to enter into a BEAR that has been started previously (Need to discuss exactly how this feature would work as it will effect time estimate)

### History page
- Ability to enter into a BEAR that has been started previously (Need to discuss exactly how this feature would work as it will effect time estimate)

### PICO search page
- Move probability % to right (replicate this anywhere that a user has to enter a percentage for consistency. Relates to #421) -25m

### Results Page
- Change plus to bear. (Need asset) - 25m
- Need different icons for completed or part way through

### Check validity 
- Outcomes are being duplicated. Steps to replicate -2h (relates to #429)
  - pico search with an outcome
  - start a bear on a paper
  - Go back to pico search, add new outcome
  - start a new bear on another paper

### Calculated results 
- ~If a user doesn’t enter any outcomes then have an unspecified outcome on the calculate results page~
- Add risk difference to the calculated statistics (was missing from the statistics form for some reason) -1h
- Add * to any stats that do not contain a 1 between the from and to values (NNT is 0 between from and to) -4h

### Relevance page
- Update how dates are stored -4h
- Change any further comments to implications for practice and text would say… what will you do now given this evidence and prior knowledge -25m
- Remove date started (completely remove) -25m
- Remove date completed input box (grab date completed by using database) - 1h

### General changes 
- Change all yes/can’t tell/no to toggles -1d

### Related to PICO search outcomes
- If no outcomes make sure a user can enter something on calculate results page. (If someone has no outcomes then a user cannot use patient specific calculations on relevance page) -1h

### General change for entire BEAR flow
- Enter to not take a user to the next page -1h

### More
- Add a quick calculation page that will allow a user to calculate stats without starting a BEAR -2h

### Missed points
- On relevance page need to add the calculation for patient specific risk. (Same formula as NNT but use risk input by user rather than calculated risk) -1h
- Posterior probability is not being calculated (Missing formula. See [comment](https://github.com/dwyl/bestevidence/issues/430#issuecomment-415766227) below) -1h

**Comment by ajburls** [comment]
@RobStallion Hi Rob, Thanks for the list. When will the items that are completed but not merged be merged for me to test?

**Comment by ajburls** [comment]
@RobStallion I will add on this issue items I come across that are missing from list to give a complete list. If these need to be added as issues, will you let me know or make an issue?
On relevance page need to add the calculation for patient specific risk. (Same formula as NNT but using inputted risk rather than calculated risk)
Posterior probability is not being calculated (do you have formula for that?)

**Comment by ajburls** [comment]
Need to make results a 2X2 table as in issue 392 remains to be done but low priority (for a future sprint)

**Comment by RobStallion** [comment]
@ajburls just wanted to answer some of your points above

> If these need to be added as issues, will you let me know or make an issue?

Adding the points here is perfect thanks. It's good to have them all in one place. I'll add them to the list at the top.

> Posterior probability is not being calculated (do you have formula for that?)

No I don't have that formula. It was not on the spreadsheet for some reason. Can you add it to the [spreadsheet](https://docs.google.com/spreadsheets/d/1zge92MFoDXkZodAqCGHPy1uR8tfgk6Qby0kq3THVyxM/edit#gid=448071614)? If not, could you just add the formula into this issue.
