### ISSUE TITLE
Messaging related bugs

### ISSUE THREAD

**Issue by iteles** [dwyl/bestevidence#460]
+ [x] On success page once a message has been sent, both admin and super admin should now see _two_ buttons:
  + [x] 'Send another message' which takes the user to the main messaging page (currently where the 'Home' button goes
  + [x] 'Home' takes super admins to the homepage for both super admins and client admins (these are different  for each!)
+ [x] For super admin, the main messages page should include either a 'Back to main menu' at the top OR the 'Back to main menu' link should be sticky at the bottom
+ [x] When a client admin is invited to be one, the email has a couple of bugs:
  + [x] The _subject_ line should be 'You have been invited to be a BestEvidence Administrator'
  + [x] The password setting link in the  email has `==` at the end, which isn't being highlighted as part of the link in most desktop mail clients - this means that the URL is incomplete when clicked and gives an internal server error

**Comment by ajburls** [comment]
@RobStallion The following work

- On success page once a message has been sent, **super admin** and **client admin** both see two buttons:
-  'Send another message' which takes the user to the main messaging page (currently where the 'Home' button goes
-  'Home' takes super admins to the homepage for both super admins and client admins (these are different for each!)

This didn't work
_-   For super admin, the main messages page should include either a 'Back to main menu' at the top OR the 'Back to main menu' link should be sticky at the bottom_

No is no back to main menu button anywhere an either client admin or super admin pages. see screenshot.

![image](https://user-images.githubusercontent.com/30235568/46133507-9c3cfd80-c238-11e8-82eb-a74253a7dd2d.png)

This works
_-  The subject line should be 'You have been invited to be a BestEvidence Administrator'_

The "==" removal has been done
_-  The password setting link in the email has == at the end, which isn't being highlighted as part of the link in most desktop mail clients - this means that the URL is incomplete when clicked and gives an internal server error_

**Comment by RobStallion** [comment]
> no back to main menu button anywhere an either client admin or super admin pages. see screenshot.

@ajburls the `back to main menu` link is now at the top of the list of users. 

<img width="336" alt="screen shot 2018-09-27 at 09 52 46" src="https://user-images.githubusercontent.com/15571853/46134585-238b7080-c23b-11e8-9996-6a6409ea2944.png">

You cannot see it in your screen shot above as your have started scrolling through the list of users.

In light of your comment, I will go with the second option @iteles suggested...
> 'Back to main menu' link should be sticky at the bottom

This way admin users will be able to see it wherever they are on that screen.

**Comment by RobStallion** [comment]
Tested with @ajburls. Closing
